### ISSUE TITLE
Navigation Maps

### ISSUE THREAD

**Issue by ilhamfajarandika** [ilhamfajarandika/Farmee-Corp#2]

**Comment by AlifinaRidaIslakhiyah** [comment]
Ilham Fajar Andika (232410103057)
Alifina Rida Islakhiyah (232410103016)
![IMG_9523](https://github.com/ilhamfajarandika/Farmee-Corp/assets/166838990/f5c97da4-39c1-4ad4-bdd2-17d2fd0d0a45)

**Comment by AlifinaRidaIslakhiyah** [comment]
Ilham Fajar Andika (232410103057)
Alifina Rida Islakhiyah (232410103016)

![IMG_9523(1)](https://github.com/ilhamfajarandika/Farmee-Corp/assets/166838990/b3ea7c9e-0429-42a6-b561-ce6c97de89c0)

**Comment by ilhamfajarandika** [comment]
[](url)

**Comment by ilhamfajarandika** [comment]
Alifina Rida Islakhiyah 		 (232410103016)
Ilham Fajar Andika		         (232410103057)

![Image](https://github.com/ilhamfajarandika/Farmee-Corp/assets/71300031/fe4b375f-ec66-4400-9d2e-735ab906924e)
