### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by AlifinaRidaIslakhiyah** [ilhamfajarandika/Farmee-Corp#5]

**Comment by ilhamfajarandika** [comment]
Vellysia Reva Nazharina		 (232410103043)
Bagus Setyo Nugroho		 (232410103065)


![Image](https://github.com/ilhamfajarandika/Farmee-Corp/assets/71300031/64079b28-b695-45fc-8e65-5e3a8e03598b)
