### ISSUE TITLE
Mockup Design

### ISSUE THREAD

**Issue by AlifinaRidaIslakhiyah** [ilhamfajarandika/Farmee-Corp#6]

**Comment by ilhamfajarandika** [comment]
- Fionella Vernanda Putri A.O (232410103021)
- Adelia Damar Cantika (232410103092)
[Wireframe Farmee Corp](https://www.figma.com/design/JpUAKUKkNXVewcpkPc3xeC/Untitled?node-id=0-1&t=oX8ovGrsh99fXtIc-0)
